// Becayis talebi olustururken "Kurum Turu" ve o kuruma bagli "Meslek"
// secimlerinde kullanilan sabit liste. Kurum listesi, memurlar.net'in
// becayis modulundeki resmi kurum listesi referans alinarak (ve guncel
// bakanlik isimleriyle) derlendi. Her kurumun meslek listesinin sonuna,
// listede olmayan bir unvan icin "Diger" secenegi eklenir.
//
// Listede ozel olarak meslek dagilimi tanimlanmamis kurumlar icin genel
// bir meslek listesi (GENEL_MESLEKLER) kullanilir.

const DIGER = "Diğer";

const GENEL_MESLEKLER = [
  "Memur",
  "Uzman",
  "Mühendis",
  "Tekniker",
  "Teknisyen",
  "Şef",
  "Avukat",
  "Bilgisayar İşletmeni",
  "Veri Hazırlama ve Kontrol İşletmeni",
  "Şoför",
  "Hizmetli",
];

// Sadece belirli kurumlar icin ozel olarak dogru/gercekci meslek listeleri.
const OZEL_MESLEKLER: Record<string, string[]> = {
  "Milli Eğitim Bakanlığı": [
    "Öğretmen",
    "Okul Müdürü",
    "Müdür Yardımcısı",
    "Rehber Öğretmen",
    "Şef",
    "Memur",
    "Hizmetli",
  ],
  "Sağlık Bakanlığı": [
    "Doktor",
    "Diş Hekimi",
    "Hemşire",
    "Ebe",
    "Eczacı",
    "Sağlık Teknisyeni",
    "Sağlık Teknikeri",
    "Diyetisyen",
    "Fizyoterapist",
    "Psikolog",
    "Sosyal Çalışmacı",
    "Memur",
  ],
  "Adalet Bakanlığı": [
    "Hakim",
    "Savcı",
    "Zabıt Katibi",
    "İcra Müdürü",
    "İcra Müdür Yardımcısı",
    "Mübaşir",
    "İnfaz ve Koruma Memuru",
    "Adli Yazı İşleri Müdürü",
    "Memur",
  ],
  "Ceza ve Tevkifevleri Genel Müdürlüğü": ["İnfaz ve Koruma Memuru", "Memur", "Psikolog", "Sosyal Çalışmacı"],
  "İçişleri Bakanlığı": ["Kaymakam", "Vali Yardımcısı", "Memur"],
  "Emniyet Genel Müdürlüğü": ["Polis Memuru", "Komiser", "Memur"],
  "Jandarma Genel Komutanlığı": ["Jandarma Erbaş/Er", "Astsubay", "Subay", "Sivil Memur"],
  "Sahil Güvenlik Komutanlığı": ["Astsubay", "Subay", "Sivil Memur"],
  "Aile ve Sosyal Hizmetler Bakanlığı": ["Sosyal Çalışmacı", "Psikolog", "Çocuk Gelişimcisi", "Bakım Elemanı", "Memur"],
  "Tarım ve Orman Bakanlığı": ["Ziraat Mühendisi", "Veteriner Hekim", "Orman Mühendisi", "Teknisyen", "Memur"],
  "Orman Genel Müdürlüğü": ["Orman Mühendisi", "Orman Muhafaza Memuru", "Memur"],
  "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı": [
    "İnşaat Mühendisi",
    "Mimar",
    "Şehir Plancısı",
    "Harita Mühendisi",
    "Memur",
  ],
  "Ulaştırma ve Altyapı Bakanlığı": ["İnşaat Mühendisi", "Elektrik-Elektronik Mühendisi", "Tekniker", "Memur"],
  "Karayolları Genel Müdürlüğü": ["İnşaat Mühendisi", "Makine Mühendisi", "Tekniker", "Şoför", "Memur"],
  "Hazine ve Maliye Bakanlığı": ["Vergi Müfettişi", "Gelir Uzmanı", "Muhasebe Yetkilisi", "Memur"],
  "Gelir İdaresi Başkanlığı": ["Vergi Müfettişi", "Gelir Uzmanı", "Memur"],
  "Çalışma ve Sosyal Güvenlik Bakanlığı": ["İş Müfettişi", "Sosyal Güvenlik Uzmanı", "Memur"],
  "Sosyal Güvenlik Kurumu": ["Sosyal Güvenlik Uzmanı", "Memur"],
  "Gençlik ve Spor Bakanlığı": ["Antrenör", "Beden Eğitimi Öğretmeni", "Memur"],
  "Spor Genel Müdürlüğü": ["Antrenör", "Memur"],
  "Kültür ve Turizm Bakanlığı": ["Müze Araştırmacısı", "Arkeolog", "Sanat Tarihçisi", "Memur"],
  "Sanayi ve Teknoloji Bakanlığı": ["Mühendis", "Sanayi ve Teknoloji Uzmanı", "Memur"],
  "Enerji ve Tabii Kaynaklar Bakanlığı": ["Maden Mühendisi", "Jeoloji Mühendisi", "Memur"],
  "Maden Tetkik ve Arama Genel Müdürlüğü": ["Jeoloji Mühendisi", "Maden Mühendisi", "Memur"],
  "Ticaret Bakanlığı": ["Gümrük Muayene Memuru", "Ticaret Uzmanı", "Memur"],
  "Dışişleri Bakanlığı": ["Diplomat", "Konsolosluk Memuru", "Memur"],
  "Milli Savunma Bakanlığı": ["Subay", "Astsubay", "Uzman Erbaş", "Sivil Memur"],
  "Kara Kuvvetleri Komutanlığı": ["Subay", "Astsubay", "Uzman Erbaş", "Sivil Memur"],
  "Hava Kuvvetleri Komutanlığı": ["Subay", "Astsubay", "Uzman Erbaş", "Sivil Memur"],
  "Deniz Kuvvetleri Komutanlığı": ["Subay", "Astsubay", "Uzman Erbaş", "Sivil Memur"],
  Belediye: [
    "Zabıta Memuru",
    "Veri Hazırlama ve Kontrol İşletmeni",
    "Mühendis",
    "Tekniker",
    "Avukat",
    "İtfaiye Eri",
    "Memur",
  ],
  Üniversite: [
    "Öğretim Üyesi",
    "Öğretim Görevlisi",
    "Araştırma Görevlisi",
    "Bilgisayar İşletmeni",
    "Teknisyen",
    "Memur",
  ],
  "Diyanet İşleri Başkanlığı": ["İmam-Hatip", "Vaiz", "Kur'an Kursu Öğreticisi", "Memur"],
  Yargıtay: ["Zabıt Katibi", "Tetkik Hakimi", "Memur"],
  PTT: ["Dağıtıcı", "Gişe Memuru", "Memur"],
  "Türkiye İş Kurumu Genel Müdürlüğü": ["İş ve Meslek Danışmanı", "Memur"],
};

export const KURUM_TURLERI: string[] = [
  "Adalet Bakanlığı",
  "Adli Tıp Kurumu Başkanlığı",
  "Afet ve Acil Durum Yönetimi Başkanlığı",
  "Aile ve Sosyal Hizmetler Bakanlığı",
  "Anayasa Mahkemesi",
  "Arsa Ofisi Genel Müdürlüğü",
  "Atatürk Kültür, Dil ve Tarih Yüksek Kurumu",
  "Bankacılık Düzenleme ve Denetleme Kurumu",
  "Basın İlan Kurumu Genel Müdürlüğü",
  "Belediye",
  "Bilgi Teknolojileri ve İletişim Kurumu",
  "Boru Hatları ile Petrol Taşıma A.Ş.",
  "Ceza ve Tevkifevleri Genel Müdürlüğü",
  "Çay İşletmeleri Genel Müdürlüğü",
  "Çevre, Şehircilik ve İklim Değişikliği Bakanlığı",
  "Çalışma ve Sosyal Güvenlik Bakanlığı",
  "Deniz Kuvvetleri Komutanlığı",
  "Devlet Arşivleri Genel Müdürlüğü",
  "Devlet Hava Meydanları İşletmesi Genel Müdürlüğü",
  "Devlet Malzeme Ofisi Genel Müdürlüğü",
  "Devlet Meteoroloji İşleri Genel Müdürlüğü",
  "Devlet Opera ve Balesi Genel Müdürlüğü",
  "Devlet Su İşleri Genel Müdürlüğü",
  "Devlet Tiyatroları Genel Müdürlüğü",
  "Dışişleri Bakanlığı",
  "Diyanet İşleri Başkanlığı",
  "Elektrik Üretim A.Ş. Genel Müdürlüğü",
  "Emniyet Genel Müdürlüğü",
  "Enerji Piyasası Düzenleme Kurumu",
  "Enerji ve Tabii Kaynaklar Bakanlığı",
  "Et ve Süt Kurumu Genel Müdürlüğü",
  "Eti Maden İşletmesi Genel Müdürlüğü",
  "Gelir İdaresi Başkanlığı",
  "Gençlik ve Spor Bakanlığı",
  "Genelkurmay Başkanlığı",
  "Halk Bankası",
  "Hava Kuvvetleri Komutanlığı",
  "Hazine ve Maliye Bakanlığı",
  "Hudut ve Sahiller Sağlık Genel Müdürlüğü",
  "İçişleri Bakanlığı",
  "İl Özel İdareleri",
  "İller Bankası Genel Müdürlüğü",
  "Jandarma Genel Komutanlığı",
  "Kara Kuvvetleri Komutanlığı",
  "Karayolları Genel Müdürlüğü",
  "Kıyı Emniyeti Genel Müdürlüğü",
  "Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi Başkanlığı",
  "Kültür ve Turizm Bakanlığı",
  "Maden Tetkik ve Arama Genel Müdürlüğü",
  "Maden ve Petrol İşleri Genel Müdürlüğü",
  "Makine ve Kimya Endüstrisi Kurumu",
  "Merkez Bankası",
  "Milli Eğitim Bakanlığı",
  "Milli Piyango İdaresi Genel Müdürlüğü",
  "Milli Savunma Bakanlığı",
  "Nüfus ve Vatandaşlık İşleri Genel Müdürlüğü",
  "Orman Genel Müdürlüğü",
  "PTT",
  "Sağlık Bakanlığı",
  "Sahil Güvenlik Komutanlığı",
  "Sanayi ve Teknoloji Bakanlığı",
  "Savunma Sanayii Başkanlığı",
  "Sivil Havacılık Genel Müdürlüğü",
  "Sosyal Güvenlik Kurumu",
  "Spor Genel Müdürlüğü",
  "Strateji ve Bütçe Başkanlığı",
  "Tapu ve Kadastro Genel Müdürlüğü",
  "Tarım İşletmeleri Genel Müdürlüğü",
  "Tarım Kredi Koop. Merkez Birliği",
  "Tarım ve Kırsal Kalkınmayı Destekleme Kurumu",
  "Tarım ve Orman Bakanlığı",
  "TCDD Taşımacılık A.Ş.",
  "Ticaret Bakanlığı",
  "Toprak Mahsulleri Ofisi Genel Müdürlüğü",
  "Türk İşbirliği ve Kalkınma İdaresi Başkanlığı",
  "Türk Patent ve Marka Kurumu",
  "Türk Standartları Enstitüsü",
  "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
  "Türkiye Cumhuriyeti Devlet Demiryolları",
  "Türkiye Elektrik Dağıtım A.Ş.",
  "Türkiye Elektrik İletim A.Ş.",
  "Türkiye İstatistik Kurumu",
  "Türkiye İş Kurumu Genel Müdürlüğü",
  "Türkiye Kömür İşletmeleri Genel Müdürlüğü",
  "Türkiye Petrolleri Anonim Ortaklığı",
  "Türkiye Şeker Fabrikaları A.Ş.",
  "Türkiye Taş Kömürü Kurumu",
  "Türkiye Yazma Eserler Kurumu Başkanlığı",
  "Türksat Uydu Haberleşme ve Kablo TV İşletme A.Ş.",
  "Ulaştırma ve Altyapı Bakanlığı",
  "Üniversite",
  "Vakıflar Genel Müdürlüğü",
  "Yargıtay",
  "Yüksek Seçim Kurulu Başkanlığı",
  "Ziraat Bankası Genel Müdürlüğü",
  DIGER + " Kamu Kurumu",
];

export const KURUM_TURU_MESLEKLERI: Record<string, string[]> = Object.fromEntries(
  KURUM_TURLERI.map((kurum) => [kurum, [...(OZEL_MESLEKLER[kurum] ?? GENEL_MESLEKLER), DIGER]]),
);

export function meslekSecenekleri(kurumTuru: string): string[] {
  return KURUM_TURU_MESLEKLERI[kurumTuru] ?? [...GENEL_MESLEKLER, DIGER];
}
