/**
 * KPSS deneme sinavi soru havuzu - Lisans duzeyi, ilk parti.
 * Her soru AI tarafindan ozgun olarak yazildi (gercek OSYM sorusu degildir).
 * secenekler: 5 sik (A-E sirayla), dogruCevap: 0-4 index.
 */
export type SeedSoru = {
  ders: "TURKCE" | "MATEMATIK" | "TARIH" | "COGRAFYA" | "VATANDASLIK" | "GUNCEL";
  soruMetni: string;
  secenekler: [string, string, string, string, string];
  dogruCevap: number;
  aciklama: string;
};

export const LISANS_SORULARI: SeedSoru[] = [
  // ---- TÜRKÇE (30) ----
  {
    ders: "TURKCE",
    soruMetni: '"Mavi" sözcüğü aşağıdaki cümlelerin hangisinde mecaz anlamda kullanılmıştır?',
    secenekler: [
      "Duvarları mavi renge boyadık.",
      "Gökyüzü bugün çok mavi görünüyor.",
      "Onun mavi bir geleceği olacağına inanıyorum.",
      "Mavi gözlü bir çocuktu.",
      "Masanın üstündeki mavi defteri aldı.",
    ],
    dogruCevap: 2,
    aciklama: '"Mavi gelecek" ifadesinde mavi, somut renk anlamından uzaklaşıp "umut verici" anlamında mecaz kullanılmıştır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?",
    secenekler: [
      "Yarın akşam size geleceğim.",
      "Bu konuda haklısın.",
      "Okula zamanında yetiş.",
      "Kitabı masanın üzerine bırakdı.",
      "Hava bugün çok soğuk.",
    ],
    dogruCevap: 3,
    aciklama: '"Bırakdı" yanlıştır; ünsüz benzeşmesi kuralınca "bırak-tı" > "bıraktı" olmalıdır.',
  },
  {
    ders: "TURKCE",
    soruMetni: '"de" bağlacının ayrı yazıldığı cümle aşağıdakilerden hangisidir?',
    secenekler: [
      "Sende bu kitaplardan var mı?",
      "O da bizimle gelecek.",
      "Evde kimse yoktu.",
      "Masada bir kalem duruyordu.",
      "Bahçede çiçekler açmış.",
    ],
    dogruCevap: 1,
    aciklama: '"O da bizimle gelecek" cümlesinde "da" bağlaç olduğu için ayrı yazılır; diğerlerinde "-de" bulunma hâli ekidir.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde büyük ünlü uyumu kuralına aykırı bir sözcük vardır?",
    secenekler: ["Kalemlik", "Gözlükçü", "Yağmurlu", "Anahtarlık", "Televizyon"],
    dogruCevap: 4,
    aciklama: '"Televizyon" Türkçe kökenli olmadığı için büyük ünlü uyumuna uymaz; diğerleri uyuma uygundur.',
  },
  {
    ders: "TURKCE",
    soruMetni: '"Kırmak" sözcüğü aşağıdaki cümlelerin hangisinde "üzmek" anlamında kullanılmıştır?',
    secenekler: [
      "Camı taşla kırdı.",
      "Sözlerimle onu kırdım.",
      "Dalı elleriyle kırdı.",
      "Bardağı yere düşürüp kırdı.",
      "Kolunu kırarak hastaneye gitti.",
    ],
    dogruCevap: 1,
    aciklama: '"Onu kırdım" cümlesinde kırmak, "üzmek, gönlünü incitmek" anlamında mecaz kullanılmıştır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Noktalama işaretlerinin kullanımıyla ilgili aşağıdaki cümlelerin hangisinde yanlışlık vardır?",
    secenekler: [
      "Ali, Veli ve Ahmet geldi.",
      "Geldin mi?",
      "Ne kadar güzel bir manzara!",
      "Annem dedi ki, yarın misafirimiz var.",
      "Kitabı, defteri ve kalemi aldım.",
    ],
    dogruCevap: 3,
    aciklama: '"Dedi ki" den sonra virgül değil doğrudan aktarılan söz gelmeli; doğrusu "Annem dedi ki: Yarın misafirimiz var." biçimindedir.',
  },
  {
    ders: "TURKCE",
    soruMetni: '"Göz" sözcüğü aşağıdakilerin hangisinde gerçek anlamıyla kullanılmıştır?',
    secenekler: [
      "Çeşmenin gözünden su akıyordu.",
      "İğnenin gözünden ipliği geçirdi.",
      "Doktor gözlerimi muayene etti.",
      "Dolabın gözüne ayakkabıları koydu.",
      "Fırının gözünde ekmek pişiyordu.",
    ],
    dogruCevap: 2,
    aciklama: "Diğer seçeneklerde göz sözcüğü mecaz/yan anlamda (kaynak, delik, bölme) kullanılmıştır; sadece bu seçenekte gerçek (organ) anlamındadır.",
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde özne gizlidir (vurgulu değildir)?",
    secenekler: [
      "Çocuklar bahçede oynuyor.",
      "Yarın erken kalkacağım.",
      "Öğretmen sınıfa girdi.",
      "Ali kitabı okudu.",
      "Rüzgâr ağaçları sallıyor.",
    ],
    dogruCevap: 1,
    aciklama: '"Yarın erken kalkacağım" cümlesinde özne fiildeki kişi ekinden anlaşılır (ben), ayrıca belirtilmemiştir; yani gizli öznedir.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde bir anlatım bozukluğu vardır?",
    secenekler: [
      "Bu kitabı okudum ve çok beğendim.",
      "Sınava hazırlanıyor ve ders çalışıyordu.",
      "Hem çalışkan hem de dürüst bir insandır.",
      "Dün akşam eve geç geldim.",
      "Yağmur yağıyor ve ıslanıyoruz.",
    ],
    dogruCevap: 1,
    aciklama: '"Sınava hazırlanıyor ve ders çalışıyordu" cümlesinde zaman uyumsuzluğu vardır (biri şimdiki, biri geçmiş zaman).',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdakilerin hangisinde isim tamlaması yoktur?",
    secenekler: ["Okul bahçesi", "Kırmızı araba", "Kitabın kapağı", "Masanın ayağı", "Evin kapısı"],
    dogruCevap: 1,
    aciklama: '"Kırmızı araba" sıfat tamlamasıdır; diğerleri isim tamlamasıdır (tamlayan-tamlanan eki alır).',
  },
  {
    ders: "TURKCE",
    soruMetni: '"Koşarak geldi." cümlesindeki altı çizili sözcüğün (koşarak) türü nedir?',
    secenekler: ["İsim-fiil", "Sıfat-fiil", "Bağ-fiil (zarf-fiil)", "Edat", "Bağlaç"],
    dogruCevap: 2,
    aciklama: '"-erek/-arak" eki bağ-fiil (zarf-fiil) ekidir; fiili zarf göreviyle başka bir fiile bağlar.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki atasözlerinden hangisi “tedbirli olmanın önemini” vurgular?",
    secenekler: [
      "Damlaya damlaya göl olur.",
      "Ateş olmayan yerden duman çıkmaz.",
      "Sakla samanı, gelir zamanı.",
      "Komşu komşunun külüne muhtaçtır.",
      "Dost acı söyler.",
    ],
    dogruCevap: 2,
    aciklama: '"Sakla samanı, gelir zamanı" sözü ileriyi düşünüp tedbirli davranmayı öğütler.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Paragrafta anlatımı canlandırmak için başvurulan, bir durumu başka bir şeye benzeterek anlatma yöntemine ne denir?",
    secenekler: ["Tanımlama", "Karşılaştırma", "Benzetme", "Örnekleme", "Tanık gösterme"],
    dogruCevap: 2,
    aciklama: "Bir kavramı ya da durumu ortak özellik üzerinden başka bir şeye benzeterek anlatma yöntemi benzetmedir.",
  },
  {
    ders: "TURKCE",
    soruMetni: "Bir paragrafın konusunu en kısa biçimde ifade eden cümleye ne ad verilir?",
    secenekler: ["Ana düşünce cümlesi", "Giriş cümlesi", "Yardımcı düşünce", "Sonuç cümlesi", "Betimleme cümlesi"],
    dogruCevap: 0,
    aciklama: "Yazarın anlatmak istediği temel fikri taşıyan cümle ana düşünce (ana fikir) cümlesidir.",
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde “ki” bağlacı bitişik yazılmıştır ve doğrudur?",
    secenekler: [
      "Sanki hiçbir şey olmamış gibi davrandı.",
      "Bu ki güzel bir fikir.",
      "O ki benim en yakın arkadaşımdır.",
      "Kapıyı açtımki kimse yoktu.",
      "Bildiğim ki bu doğru değil.",
    ],
    dogruCevap: 0,
    aciklama: '"Sanki" kalıplaşmış bir sözcüktür ve bitişik yazılır; bağlaç olan "ki" genelde ayrı yazılır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde pekiştirme sıfatı kullanılmıştır?",
    secenekler: [
      "Bu çok güzel bir elbise.",
      "Masmavi bir deniz gördük.",
      "İki kalem aldım.",
      "Kırmızı bir gül kopardı.",
      "Uzun bir yoldan geldik.",
    ],
    dogruCevap: 1,
    aciklama: '"Masmavi" sözcüğü "mavi" sıfatının pekiştirilmiş biçimidir (m+as ekiyle).',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisi öznel bir yargı bildirir?",
    secenekler: [
      "Bu şehirde yılda ortalama 800 mm yağış düşer.",
      "Roman 300 sayfadan oluşuyor.",
      "Bence bu, yazarın en güzel eseri.",
      "Toplantı saat 10.00’da başladı.",
      "Türkiye'nin başkenti Ankara'dır.",
    ],
    dogruCevap: 2,
    aciklama: '"Bence" ifadesiyle kişisel görüş belirtildiği için bu cümle öznel (kanıtlanamaz) bir yargı taşır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde “ile” sözcüğü bağlaç görevindedir?",
    secenekler: [
      "Kalemle yazı yazdı.",
      "Ahmet ile Mehmet okula gitti.",
      "Trenle şehre gitti.",
      "Bıçakla ekmek kesti.",
      "Arabayla geldi.",
    ],
    dogruCevap: 1,
    aciklama: '"Ahmet ile Mehmet" iki ismi bağladığı için "ile" burada bağlaç görevindedir; diğerlerinde araç/vasıta anlamı taşıyan çekim edatıdır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Bir metinde yazarın okuyucuyu bir konuda ikna etmeye çalıştığı anlatım biçimi aşağıdakilerden hangisidir?",
    secenekler: ["Öyküleyici anlatım", "Betimleyici anlatım", "Açıklayıcı anlatım", "Tartışmacı anlatım", "Emredici anlatım"],
    dogruCevap: 3,
    aciklama: "Yazarın bir görüşü savunup okuyucuyu ikna etmeye çalıştığı anlatım biçimi tartışmacı anlatımdır.",
  },
  {
    ders: "TURKCE",
    soruMetni: '"Hukuk" sözcüğü aşağıdaki cümlelerin hangisinde terim anlamıyla kullanılmıştır?',
    secenekler: [
      "Onunla eski bir hukukumuz var.",
      "Hukuk Fakültesinden yeni mezun oldu.",
      "Komşuluk hukukuna uymalıyız.",
      "Aramızdaki dostluk hukuku bozulmasın.",
      "Yıllara dayanan bir hukukumuz vardı.",
    ],
    dogruCevap: 1,
    aciklama: '"Hukuk Fakültesi" ifadesinde hukuk, bir bilim dalının adı olarak terim anlamında kullanılmıştır; diğerlerinde "dostluk, bağ" anlamındadır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "“Yüz” sözcüğü aşağıdaki cümlelerin hangisinde “sayı” anlamında kullanılmıştır?",
    secenekler: [
      "Yüzünü yıkadı.",
      "Yüz kişi sınava girdi.",
      "Yüzünde bir gülümseme vardı.",
      "Nehirde yüzdü.",
      "Elbisenin yüzü yırtılmış.",
    ],
    dogruCevap: 1,
    aciklama: '"Yüz" burada 100 sayısı anlamında kullanılmıştır; diğer cümlelerde "yüz" farklı anlamlardadır (eş seslilik örneği).',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde amaç-sonuç ilişkisi vardır?",
    secenekler: [
      "Yorgun olduğu için erken yattı.",
      "Kitap okumak için kütüphaneye gitti.",
      "Yağmur yağınca sokaklar ıslandı.",
      "Hastalandığından okula gidemedi.",
      "Param olmadığından alışveriş yapamadım.",
    ],
    dogruCevap: 1,
    aciklama: '"Kitap okumak için" ifadesi amaç bildirir; diğer cümlelerde sebep-sonuç ilişkisi vardır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisi şart (koşul) cümlesidir?",
    secenekler: [
      "Çalışırsan başarırsın.",
      "Çalıştı ve başardı.",
      "Çalışmadığı hâlde başardı.",
      "Çalışırken müzik dinler.",
      "Çalışmak için erken kalktı.",
    ],
    dogruCevap: 0,
    aciklama: '"-sa/-se" şart ekiyle kurulan "Çalışırsan başarırsın" cümlesi koşul bildirir.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdakilerin hangisinde edat (ilgeç) kullanılmıştır?",
    secenekler: ["Okula gitti.", "Senin için geldim.", "Hızlı koştu.", "Kitabı okudu.", "Çok güzel bir gün."],
    dogruCevap: 1,
    aciklama: '"İçin" sözcüğü tek başına anlamı olmayan, başka sözcüklerle ilişki kuran bir edattır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde birleşik zamanlı fiil kullanılmıştır?",
    secenekler: ["Geldi.", "Gelmişti.", "Gelecek.", "Geliyor.", "Gelir."],
    dogruCevap: 1,
    aciklama: '"Gelmişti" (gelmiş+idi) hikâye birleşik zamanı örneğidir; bu yapıda iki zaman eki bir araya gelir.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde abartma (mübalağa) sanatına başvurulmuştur?",
    secenekler: [
      "Bahçede güller açmıştı.",
      "Gözyaşlarından bir göl oluştu.",
      "Kuşlar gökyüzünde uçuyordu.",
      "Çocuklar parkta oynuyordu.",
      "Rüzgâr yapraklara dokunuyordu.",
    ],
    dogruCevap: 1,
    aciklama: "Gözyaşının göl oluşturması gerçekte mümkün olmayan bir abartmadır.",
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde soru anlamı, soru eki olmadan sağlanmıştır?",
    secenekler: ["Geldin mi?", "Bunu sen mi yaptın?", "Nereye gidiyorsun?", "Okudun mu?", "Yorgun musun?"],
    dogruCevap: 2,
    aciklama: '"Nereye gidiyorsun?" cümlesinde soru, "mi" soru eki değil "nereye" soru sözcüğüyle sağlanmıştır.',
  },
  {
    ders: "TURKCE",
    soruMetni: "Bir metinde yazarın okuru bilgilendirmek amacıyla nesnel biçimde bilgi verdiği anlatım biçimi nedir?",
    secenekler: ["Açıklayıcı anlatım", "Öyküleyici anlatım", "Betimleyici anlatım", "Tartışmacı anlatım", "Coşku ve heyecana bağlı anlatım"],
    dogruCevap: 0,
    aciklama: "Bilgi vermek amacıyla nesnel biçimde yazılan metinlerde açıklayıcı anlatım kullanılır.",
  },
  {
    ders: "TURKCE",
    soruMetni: "Aşağıdaki cümlelerin hangisinde “ünlü düşmesi” örneği vardır?",
    secenekler: ["Kitap-ı", "Burun-u (burnu)", "Ev-e", "Göz-ü", "Kol-u"],
    dogruCevap: 1,
    aciklama: '"Burun" sözcüğü ek alırken ikinci hecedeki dar ünlü düşer: burun+u > burnu.',
  },
  {
    ders: "TURKCE",
    soruMetni: '"Kitabı masaya koydu." cümlesinde altı çizili "masaya" sözcüğünün cümledeki görevi nedir?',
    secenekler: ["Özne", "Nesne", "Dolaylı tümleç", "Zarf tümleci", "Yüklem"],
    dogruCevap: 2,
    aciklama: '"-e/-a" hâl ekini alan ve yüklemin yöneldiği yeri bildiren "masaya" sözcüğü dolaylı tümleçtir.',
  },

  // ---- MATEMATİK (30) ----
  {
    ders: "MATEMATIK",
    soruMetni: "3 + 5 × 2 - 4 işleminin sonucu kaçtır?",
    secenekler: ["9", "12", "16", "6", "11"],
    dogruCevap: 0,
    aciklama: "İşlem önceliğine göre önce çarpma yapılır: 5×2=10, sonra 3+10-4=9.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir sayının %20'si 40 olduğuna göre bu sayı kaçtır?",
    secenekler: ["160", "180", "200", "220", "240"],
    dogruCevap: 2,
    aciklama: "x × 0,20 = 40 ⟹ x = 200.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "15 işçi bir işi 12 günde bitiriyor. Aynı işi 9 işçi kaç günde bitirir?",
    secenekler: ["15", "18", "20", "22", "25"],
    dogruCevap: 2,
    aciklama: "İşçi-gün sabittir: 15×12=180. 180÷9=20 gün.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "İki basamaklı en büyük asal sayı kaçtır?",
    secenekler: ["89", "91", "93", "97", "99"],
    dogruCevap: 3,
    aciklama: "91=7×13 ve 93, 99 asal değildir; 97 iki basamaklı en büyük asal sayıdır.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "24 ve 36 sayılarının EBOB'u (en büyük ortak bölen) kaçtır?",
    secenekler: ["4", "6", "8", "12", "18"],
    dogruCevap: 3,
    aciklama: "24=2³×3, 36=2²×3²; ortak asal çarpanların en küçük üslüleri çarpılır: 2²×3=12.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "8 ve 12 sayılarının EKOK'u (en küçük ortak kat) kaçtır?",
    secenekler: ["16", "20", "24", "36", "48"],
    dogruCevap: 2,
    aciklama: "8=2³, 12=2²×3; en büyük üslüler çarpılır: 2³×3=24.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir ürünün fiyatı önce %10 artırılıyor, sonra yeni fiyat %10 indiriliyor. Son fiyat ilk fiyata göre nasıl değişmiştir?",
    secenekler: ["%1 azalmıştır", "%1 artmıştır", "Değişmemiştir", "%10 artmıştır", "%20 azalmıştır"],
    dogruCevap: 0,
    aciklama: "1,10 × 0,90 = 0,99 olduğundan son fiyat ilk fiyatın %99'udur, yani %1 azalmıştır.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "x + 7 = 15 denklemine göre x kaçtır?",
    secenekler: ["6", "7", "8", "9", "10"],
    dogruCevap: 2,
    aciklama: "x = 15 - 7 = 8.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "3x - 5 = 16 denklemine göre x kaçtır?",
    secenekler: ["5", "6", "7", "8", "9"],
    dogruCevap: 2,
    aciklama: "3x = 21 ⟹ x = 7.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Uzun kenarı 12 cm, kısa kenarı 7 cm olan bir dikdörtgenin çevresi kaç cm'dir?",
    secenekler: ["19", "32", "38", "42", "84"],
    dogruCevap: 2,
    aciklama: "Çevre = 2×(12+7) = 38 cm.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Alanı 49 cm² olan bir karenin bir kenarı kaç cm'dir?",
    secenekler: ["6", "6,5", "7", "7,5", "8"],
    dogruCevap: 2,
    aciklama: "√49 = 7 cm.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Yarıçapı 7 cm olan bir dairenin çevresi kaç cm'dir? (π=22/7 alınız)",
    secenekler: ["22", "33", "44", "49", "154"],
    dogruCevap: 2,
    aciklama: "Çevre = 2πr = 2×(22/7)×7 = 44 cm.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "5 sayısının küpü (5³) kaçtır?",
    secenekler: ["15", "25", "75", "100", "125"],
    dogruCevap: 4,
    aciklama: "5³ = 5×5×5 = 125.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "√144 kaçtır?",
    secenekler: ["10", "11", "12", "13", "14"],
    dogruCevap: 2,
    aciklama: "12×12=144 olduğundan √144=12.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir sınıfta 20 erkek, 15 kız öğrenci vardır. Kız öğrencilerin tüm sınıfa oranı kaçtır?",
    secenekler: ["3/7", "3/5", "15/20", "4/7", "1/3"],
    dogruCevap: 0,
    aciklama: "Toplam öğrenci 35; kızların oranı 15/35 = 3/7.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "İki sayının toplamı 50, farkı 10'dur. Büyük sayı kaçtır?",
    secenekler: ["20", "25", "28", "30", "35"],
    dogruCevap: 3,
    aciklama: "Büyük sayı = (toplam+fark)/2 = (50+10)/2 = 30.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir otomobil 120 km yolu 2 saatte aldığına göre hızı kaç km/saattir?",
    secenekler: ["40", "50", "60", "70", "80"],
    dogruCevap: 2,
    aciklama: "Hız = yol/zaman = 120/2 = 60 km/saat.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "240 km'lik yolu saatte 80 km hızla giden bir araç bu yolu kaç saatte tamamlar?",
    secenekler: ["2", "2,5", "3", "3,5", "4"],
    dogruCevap: 2,
    aciklama: "Zaman = yol/hız = 240/80 = 3 saat.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "100 sayısının %35'i kaçtır?",
    secenekler: ["25", "30", "35", "40", "45"],
    dogruCevap: 2,
    aciklama: "100 × 0,35 = 35.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir sayının yarısının 3 fazlası 18 olduğuna göre bu sayı kaçtır?",
    secenekler: ["24", "27", "30", "33", "36"],
    dogruCevap: 2,
    aciklama: "x/2 + 3 = 18 ⟹ x/2 = 15 ⟹ x = 30.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "2, 4, 6, 8, ... şeklinde devam eden dizinin 10. terimi kaçtır?",
    secenekler: ["16", "18", "20", "22", "24"],
    dogruCevap: 2,
    aciklama: "Genel terim 2n'dir; n=10 için 2×10=20.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "3 kalemin fiyatı 18 TL ise 7 kalemin fiyatı kaç TL'dir?",
    secenekler: ["36", "38", "40", "42", "44"],
    dogruCevap: 3,
    aciklama: "Bir kalem 18/3=6 TL; 7 kalem 7×6=42 TL.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir havuzu bir musluk tek başına 6 saatte, başka bir musluk tek başına 3 saatte dolduruyor. İki musluk birlikte açılırsa havuz kaç saatte dolar?",
    secenekler: ["1", "1,5", "2", "2,5", "3"],
    dogruCevap: 2,
    aciklama: "Saatlik doldurma oranları toplanır: 1/6 + 1/3 = 1/2; havuz 2 saatte dolar.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "7! (7 faktöriyel) işleminin sonucu kaçtır?",
    secenekler: ["720", "2520", "5040", "40320", "120"],
    dogruCevap: 2,
    aciklama: "7! = 7×6×5×4×3×2×1 = 5040.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Hileli olmayan bir zarın bir kez atılmasında çift sayı gelme olasılığı kaçtır?",
    secenekler: ["1/6", "1/3", "1/2", "2/3", "5/6"],
    dogruCevap: 2,
    aciklama: "Çift sayılar {2,4,6} olduğundan olasılık 3/6=1/2'dir.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "45 sayısının asal çarpanlarına ayrılmış hâli aşağıdakilerden hangisidir?",
    secenekler: ["3²×5", "3×5²", "3×15", "5×9", "2×3²×5"],
    dogruCevap: 0,
    aciklama: "45 = 9×5 = 3²×5.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir üçgenin iç açıları toplamı kaç derecedir?",
    secenekler: ["90", "120", "180", "270", "360"],
    dogruCevap: 2,
    aciklama: "Her üçgende iç açılar toplamı 180 derecedir.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Yarıçapı 5 cm olan bir dairenin alanı kaç cm²'dir? (π=3 alınız)",
    secenekler: ["15", "30", "45", "75", "100"],
    dogruCevap: 3,
    aciklama: "Alan = π×r² = 3×5² = 3×25 = 75 cm².",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "5 sayısının 3 fazlasının 2 katı kaçtır?",
    secenekler: ["10", "13", "14", "16", "18"],
    dogruCevap: 3,
    aciklama: "(5+3)×2 = 8×2 = 16.",
  },
  {
    ders: "MATEMATIK",
    soruMetni: "Bir sayının 4 katının 5 eksiği 27 olduğuna göre bu sayı kaçtır?",
    secenekler: ["6", "7", "8", "9", "10"],
    dogruCevap: 2,
    aciklama: "4x - 5 = 27 ⟹ 4x = 32 ⟹ x = 8.",
  },

  // ---- TARİH (27) ----
  {
    ders: "TARIH",
    soruMetni: "Türkiye Büyük Millet Meclisi (TBMM) hangi tarihte açılmıştır?",
    secenekler: ["19 Mayıs 1919", "23 Nisan 1920", "29 Ekim 1923", "20 Ocak 1921", "11 Ekim 1922"],
    dogruCevap: 1,
    aciklama: "TBMM 23 Nisan 1920'de Ankara'da açılmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Türkiye Cumhuriyeti hangi tarihte ilan edilmiştir?",
    secenekler: ["1 Kasım 1922", "24 Temmuz 1923", "29 Ekim 1923", "3 Mart 1924", "30 Ağustos 1922"],
    dogruCevap: 2,
    aciklama: "Cumhuriyet, 29 Ekim 1923'te ilan edilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Lozan Barış Antlaşması hangi tarihte imzalanmıştır?",
    secenekler: ["11 Ekim 1922", "24 Temmuz 1923", "29 Ekim 1923", "20 Kasım 1922", "21 Haziran 1923"],
    dogruCevap: 1,
    aciklama: "Lozan Barış Antlaşması 24 Temmuz 1923'te imzalanmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Saltanat hangi tarihte kaldırılmıştır?",
    secenekler: ["1 Kasım 1922", "29 Ekim 1923", "3 Mart 1924", "11 Ekim 1922", "30 Ekim 1918"],
    dogruCevap: 0,
    aciklama: "Saltanat, TBMM kararıyla 1 Kasım 1922'de kaldırılmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Halifelik hangi tarihte kaldırılmıştır?",
    secenekler: ["1 Kasım 1922", "29 Ekim 1923", "3 Mart 1924", "20 Nisan 1924", "1 Kasım 1928"],
    dogruCevap: 2,
    aciklama: "Halifelik 3 Mart 1924'te kaldırılmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Mustafa Kemal Atatürk, Kurtuluş Savaşı'nın başlangıcı kabul edilen Samsun'a hangi tarihte çıkmıştır?",
    secenekler: ["19 Mayıs 1919", "23 Temmuz 1919", "4 Eylül 1919", "22 Haziran 1919", "15 Mayıs 1919"],
    dogruCevap: 0,
    aciklama: "Mustafa Kemal, 19 Mayıs 1919'da Samsun'a çıkmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Aşağıdakilerden hangisi Kurtuluş Savaşı'nda Yunan ordusunun geri çekilmeye başladığı dönüm noktası olan meydan muharebesidir?",
    secenekler: ["I. İnönü Muharebesi", "II. İnönü Muharebesi", "Sakarya Meydan Muharebesi", "Büyük Taarruz", "Çanakkale Muharebeleri"],
    dogruCevap: 2,
    aciklama: "Sakarya Meydan Muharebesi (1921) sonrası Yunan ordusu savunmaya ve geri çekilmeye yönelmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Büyük Taarruz hangi tarihte başlamıştır?",
    secenekler: ["23 Ağustos 1921", "26 Ağustos 1922", "30 Ağustos 1922", "9 Eylül 1922", "11 Ekim 1922"],
    dogruCevap: 1,
    aciklama: "Büyük Taarruz 26 Ağustos 1922'de başlamıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Başkomutanlık Meydan Muharebesi (Dumlupınar Meydan Muharebesi) hangi tarihte kazanılmıştır?",
    secenekler: ["26 Ağustos 1922", "30 Ağustos 1922", "9 Eylül 1922", "11 Ekim 1922", "19 Mayıs 1919"],
    dogruCevap: 1,
    aciklama: "Başkomutanlık Meydan Muharebesi 30 Ağustos 1922'de kazanılmıştır; bu gün Zafer Bayramı olarak kutlanır.",
  },
  {
    ders: "TARIH",
    soruMetni: "İzmir, düşman işgalinden hangi tarihte kurtarılmıştır?",
    secenekler: ["26 Ağustos 1922", "30 Ağustos 1922", "9 Eylül 1922", "11 Ekim 1922", "24 Temmuz 1923"],
    dogruCevap: 2,
    aciklama: "İzmir 9 Eylül 1922'de kurtarılmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Mudanya Ateşkes (Mütarekesi) Antlaşması hangi tarihte imzalanmıştır?",
    secenekler: ["9 Eylül 1922", "11 Ekim 1922", "20 Kasım 1922", "24 Temmuz 1923", "1 Kasım 1922"],
    dogruCevap: 1,
    aciklama: "Mudanya Ateşkes Antlaşması 11 Ekim 1922'de imzalanmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Erzurum Kongresi hangi yıl toplanmıştır?",
    secenekler: ["1918", "1919", "1920", "1921", "1922"],
    dogruCevap: 1,
    aciklama: "Erzurum Kongresi 23 Temmuz - 7 Ağustos 1919 tarihleri arasında toplanmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Sivas Kongresi hangi tarihler arasında toplanmıştır?",
    secenekler: ["23 Temmuz - 7 Ağustos 1919", "4-11 Eylül 1919", "22 Haziran 1919", "28 Ocak 1920", "20 Ocak 1921"],
    dogruCevap: 1,
    aciklama: "Sivas Kongresi 4-11 Eylül 1919 tarihleri arasında toplanmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Kurtuluş Savaşı'nın hazırlık (örgütlenme) sürecinin başlangıcı kabul edilen genelge aşağıdakilerden hangisidir?",
    secenekler: ["Amasya Genelgesi", "Misak-ı Milli", "Teşkilat-ı Esasiye", "Sivas Kongresi Bildirisi", "Lozan Antlaşması"],
    dogruCevap: 0,
    aciklama: "22 Haziran 1919'da yayımlanan Amasya Genelgesi, milli mücadelenin örgütlenme sürecinin başlangıcı sayılır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Misak-ı Millî (Millî Ant) hangi tarihte kabul edilmiştir?",
    secenekler: ["22 Haziran 1919", "4 Eylül 1919", "28 Ocak 1920", "23 Nisan 1920", "20 Ocak 1921"],
    dogruCevap: 2,
    aciklama: "Misak-ı Millî, son Osmanlı Mebuslar Meclisi'nce 28 Ocak 1920'de kabul edilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "TBMM'nin ilk anayasası olan Teşkilat-ı Esasiye Kanunu hangi tarihte kabul edilmiştir?",
    secenekler: ["23 Nisan 1920", "20 Ocak 1921", "29 Ekim 1923", "20 Nisan 1924", "1 Kasım 1922"],
    dogruCevap: 1,
    aciklama: "Teşkilat-ı Esasiye Kanunu 20 Ocak 1921'de kabul edilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Türkiye Cumhuriyeti'nin ilk Cumhurbaşkanı kimdir?",
    secenekler: ["İsmet İnönü", "Mustafa Kemal Atatürk", "Celal Bayar", "Fevzi Çakmak", "Kazım Karabekir"],
    dogruCevap: 1,
    aciklama: "Cumhuriyet'in ilanıyla birlikte 29 Ekim 1923'te Mustafa Kemal Atatürk ilk Cumhurbaşkanı seçilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Soyadı Kanunu hangi yıl kabul edilmiştir?",
    secenekler: ["1928", "1930", "1932", "1934", "1936"],
    dogruCevap: 3,
    aciklama: "Soyadı Kanunu 21 Haziran 1934'te kabul edilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Türkiye'de kadınlara milletvekili seçme ve seçilme hakkı hangi yıl tanınmıştır?",
    secenekler: ["1930", "1933", "1934", "1935", "1938"],
    dogruCevap: 2,
    aciklama: "Kadınlara milletvekili seçme ve seçilme hakkı 5 Aralık 1934'te tanınmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Yeni Türk alfabesinin (Latin harflerinin) kabulü hangi yıl gerçekleşmiştir?",
    secenekler: ["1923", "1924", "1925", "1928", "1930"],
    dogruCevap: 3,
    aciklama: "Harf İnkılabı ile yeni Türk alfabesi 1 Kasım 1928'de kabul edilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Mustafa Kemal Atatürk hangi tarihte vefat etmiştir?",
    secenekler: ["10 Kasım 1938", "19 Mayıs 1938", "29 Ekim 1938", "1 Kasım 1938", "23 Nisan 1938"],
    dogruCevap: 0,
    aciklama: "Atatürk, 10 Kasım 1938'de Dolmabahçe Sarayı'nda vefat etmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Osmanlı Devleti geleneksel olarak hangi yılda kurulmuş kabul edilir?",
    secenekler: ["1071", "1299", "1453", "1512", "1326"],
    dogruCevap: 1,
    aciklama: "Osmanlı Devleti'nin kuruluşu geleneksel olarak 1299 kabul edilir.",
  },
  {
    ders: "TARIH",
    soruMetni: "İstanbul'un fethi hangi tarihte, hangi padişah tarafından gerçekleştirilmiştir?",
    secenekler: [
      "1453, Fatih Sultan Mehmet",
      "1453, II. Bayezid",
      "1517, Yavuz Sultan Selim",
      "1389, I. Murad",
      "1402, Yıldırım Bayezid",
    ],
    dogruCevap: 0,
    aciklama: "İstanbul, 29 Mayıs 1453'te Fatih Sultan Mehmet tarafından fethedilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Malazgirt Meydan Muharebesi hangi yıl, hangi Selçuklu hükümdarı önderliğinde kazanılmıştır?",
    secenekler: [
      "1071, Alparslan",
      "1176, II. Kılıçarslan",
      "1243, II. Gıyaseddin Keyhüsrev",
      "1040, Tuğrul Bey",
      "1299, Osman Bey",
    ],
    dogruCevap: 0,
    aciklama: "Malazgirt Meydan Muharebesi 1071'de Büyük Selçuklu Sultanı Alparslan önderliğinde kazanılmış, Anadolu'nun kapıları Türklere açılmıştır.",
  },
  {
    ders: "TARIH",
    soruMetni: "Osmanlı Devleti'nde ilan edilen Tanzimat Fermanı hangi yüzyılda gerçekleşmiştir?",
    secenekler: ["17. yüzyıl", "18. yüzyıl", "19. yüzyıl", "20. yüzyıl başı", "16. yüzyıl"],
    dogruCevap: 2,
    aciklama: "Tanzimat Fermanı 1839'da, 19. yüzyılda ilan edilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Osmanlı'da ilk kez bir anayasanın (Kanun-i Esasi) ilan edildiği I. Meşrutiyet hangi yıl ilan edilmiştir?",
    secenekler: ["1839", "1856", "1876", "1908", "1909"],
    dogruCevap: 2,
    aciklama: "I. Meşrutiyet 1876'da ilan edilmiştir.",
  },
  {
    ders: "TARIH",
    soruMetni: "Osmanlı Devleti, I. Dünya Savaşı'na hangi yıl fiilen katılmıştır?",
    secenekler: ["1912", "1913", "1914", "1917", "1918"],
    dogruCevap: 2,
    aciklama: "Osmanlı Devleti, 1914 yılının sonlarında I. Dünya Savaşı'na katılmıştır.",
  },

  // ---- COĞRAFYA (18) ----
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'nin nüfus bakımından en kalabalık ili aşağıdakilerden hangisidir?",
    secenekler: ["Ankara", "İzmir", "İstanbul", "Bursa", "Antalya"],
    dogruCevap: 2,
    aciklama: "İstanbul, Türkiye'nin en kalabalık ilidir.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'nin en yüksek dağı aşağıdakilerden hangisidir?",
    secenekler: ["Erciyes Dağı", "Uludağ", "Kaçkar Dağı", "Ağrı Dağı", "Nemrut Dağı"],
    dogruCevap: 3,
    aciklama: "5137 m yüksekliğindeki Ağrı Dağı, Türkiye'nin en yüksek dağıdır.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'nin sınırları içinde en uzun akan nehri aşağıdakilerden hangisidir?",
    secenekler: ["Fırat", "Sakarya", "Kızılırmak", "Yeşilırmak", "Dicle"],
    dogruCevap: 2,
    aciklama: "Kızılırmak, tamamı Türkiye sınırları içinde akan en uzun nehirdir.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'nin en büyük gölü aşağıdakilerden hangisidir?",
    secenekler: ["Tuz Gölü", "Beyşehir Gölü", "Eğirdir Gölü", "Van Gölü", "İznik Gölü"],
    dogruCevap: 3,
    aciklama: "Van Gölü, yüzölçümü bakımından Türkiye'nin en büyük gölüdür.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'nin kara sınırı komşusu olan ülke sayısı kaçtır?",
    secenekler: ["6", "7", "8", "9", "10"],
    dogruCevap: 2,
    aciklama: "Türkiye; Yunanistan, Bulgaristan, Gürcistan, Ermenistan, Azerbaycan (Nahçıvan), İran, Irak ve Suriye olmak üzere 8 ülkeyle kara sınırı komşusudur.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye kaç coğrafi bölgeye ayrılmıştır?",
    secenekler: ["5", "6", "7", "8", "9"],
    dogruCevap: 2,
    aciklama: "Türkiye; Marmara, Ege, Akdeniz, İç Anadolu, Karadeniz, Doğu Anadolu ve Güneydoğu Anadolu olmak üzere 7 coğrafi bölgeye ayrılmıştır.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Yazları sıcak ve kurak, kışları ılık ve yağışlı geçen iklim tipi Türkiye'de en belirgin biçimde hangi kıyılarda görülür?",
    secenekler: ["Karadeniz kıyıları", "Marmara kıyıları", "Akdeniz ve Ege kıyıları", "Doğu Anadolu", "İç Anadolu"],
    dogruCevap: 2,
    aciklama: "Akdeniz iklimi, Akdeniz ve Ege kıyılarında görülür; yazlar sıcak-kurak, kışlar ılık-yağışlıdır.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Her mevsim yağışlı, yazları serin kışları ılıman geçen iklim tipi Türkiye'de hangi bölgede görülür?",
    secenekler: ["İç Anadolu", "Karadeniz Bölgesi", "Güneydoğu Anadolu", "Akdeniz Bölgesi", "Doğu Anadolu"],
    dogruCevap: 1,
    aciklama: "Karadeniz iklimi her mevsim yağışlıdır; yazlar serin, kışlar ise diğer iç kesimlere göre ılımandır.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Yüzölçümü bakımından Türkiye'nin en büyük coğrafi bölgesi aşağıdakilerden hangisidir?",
    secenekler: ["Karadeniz Bölgesi", "İç Anadolu Bölgesi", "Doğu Anadolu Bölgesi", "Akdeniz Bölgesi", "Ege Bölgesi"],
    dogruCevap: 2,
    aciklama: "Doğu Anadolu Bölgesi, yüzölçümü bakımından Türkiye'nin en büyük bölgesidir.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Yüzölçümü bakımından Türkiye'nin en küçük coğrafi bölgesi aşağıdakilerden hangisidir?",
    secenekler: ["Ege Bölgesi", "Marmara Bölgesi", "Güneydoğu Anadolu Bölgesi", "Akdeniz Bölgesi", "Karadeniz Bölgesi"],
    dogruCevap: 1,
    aciklama: "Marmara Bölgesi, yüzölçümü bakımından Türkiye'nin en küçük coğrafi bölgesidir.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye Cumhuriyeti'nin başkenti aşağıdakilerden hangisidir?",
    secenekler: ["İstanbul", "İzmir", "Ankara", "Bursa", "Konya"],
    dogruCevap: 2,
    aciklama: "Türkiye'nin başkenti Ankara'dır (13 Ekim 1923'te başkent ilan edilmiştir).",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Fırat ve Dicle nehirleri birleşerek hangi körfeze dökülür?",
    secenekler: ["Basra Körfezi", "Kızıldeniz", "Umman Denizi", "Hazar Denizi", "Akabe Körfezi"],
    dogruCevap: 0,
    aciklama: "Fırat ve Dicle, Irak topraklarında birleşip Şattularab adıyla Basra Körfezi'ne dökülür.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'de nüfus yoğunluğunun en fazla olduğu coğrafi bölge aşağıdakilerden hangisidir?",
    secenekler: ["Ege Bölgesi", "Marmara Bölgesi", "Akdeniz Bölgesi", "Karadeniz Bölgesi", "İç Anadolu Bölgesi"],
    dogruCevap: 1,
    aciklama: "Sanayi ve İstanbul'un yoğun nüfusu nedeniyle Marmara Bölgesi en yüksek nüfus yoğunluğuna sahiptir.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "İstanbul Boğazı hangi iki denizi birbirine bağlar?",
    secenekler: [
      "Ege Denizi - Akdeniz",
      "Karadeniz - Marmara Denizi",
      "Marmara Denizi - Ege Denizi",
      "Akdeniz - Kızıldeniz",
      "Karadeniz - Ege Denizi",
    ],
    dogruCevap: 1,
    aciklama: "İstanbul Boğazı, Karadeniz ile Marmara Denizi'ni birbirine bağlar.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Çanakkale Boğazı hangi iki denizi birbirine bağlar?",
    secenekler: [
      "Karadeniz - Marmara Denizi",
      "Marmara Denizi - Ege Denizi",
      "Ege Denizi - Akdeniz",
      "Akdeniz - Marmara Denizi",
      "Karadeniz - Ege Denizi",
    ],
    dogruCevap: 1,
    aciklama: "Çanakkale Boğazı, Marmara Denizi ile Ege Denizi'ni birbirine bağlar.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'nin en büyük adası aşağıdakilerden hangisidir?",
    secenekler: ["Bozcaada", "Marmara Adası", "Gökçeada", "Avşa Adası", "Büyükada"],
    dogruCevap: 2,
    aciklama: "Gökçeada, yüzölçümü bakımından Türkiye'nin en büyük adasıdır.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Türkiye'de il sayısı kaçtır?",
    secenekler: ["73", "77", "79", "81", "83"],
    dogruCevap: 3,
    aciklama: "Türkiye'de 81 il bulunmaktadır.",
  },
  {
    ders: "COGRAFYA",
    soruMetni: "Denizden uzak, karasal iklim özellikleri nedeniyle yazları sıcak-kurak, kışları soğuk ve kar yağışlı geçen, yağışın en az olduğu bölgelerden biri aşağıdakilerden hangisidir?",
    secenekler: ["Karadeniz Bölgesi", "Marmara Bölgesi", "Ege Bölgesi", "İç Anadolu Bölgesi", "Akdeniz Bölgesi"],
    dogruCevap: 3,
    aciklama: "İç Anadolu Bölgesi karasal iklimin etkisiyle en az yağış alan bölgelerden biridir.",
  },

  // ---- VATANDAŞLIK (9) ----
  {
    ders: "VATANDASLIK",
    soruMetni: "Türkiye Cumhuriyeti Anayasası'na göre yasama yetkisi hangi organa aittir?",
    secenekler: [
      "Cumhurbaşkanlığı",
      "Türkiye Büyük Millet Meclisi",
      "Bakanlar Kurulu",
      "Anayasa Mahkemesi",
      "Yargıtay",
    ],
    dogruCevap: 1,
    aciklama: "Anayasa'nın 7. maddesine göre yasama yetkisi Türk Milleti adına TBMM'ye aittir.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "Türkiye'de yargı yetkisi kimin/kimlerin adına kullanılır?",
    secenekler: ["Cumhurbaşkanı adına", "TBMM adına", "Türk Milleti adına", "Anayasa Mahkemesi adına", "Hükûmet adına"],
    dogruCevap: 2,
    aciklama: "Anayasa'nın 9. maddesine göre yargı yetkisi Türk Milleti adına bağımsız mahkemelerce kullanılır.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "Türkiye Cumhuriyeti Anayasası'na göre Türkiye Devleti'nin şekli nedir?",
    secenekler: ["Monarşi", "Cumhuriyet", "Teokrasi", "Konfederasyon", "Federasyon"],
    dogruCevap: 1,
    aciklama: "Anayasa'nın 1. maddesine göre Türkiye Devleti bir Cumhuriyettir.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "TBMM üyeleri kaç yılda bir yapılan seçimlerle belirlenir?",
    secenekler: ["3", "4", "5", "6", "7"],
    dogruCevap: 2,
    aciklama: "Türkiye Büyük Millet Meclisi seçimleri beş yılda bir yapılır.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "Anayasa Mahkemesi öncelikle hangi görevi yerine getirir?",
    secenekler: [
      "Kanunların Anayasaya uygunluğunu denetlemek",
      "Yerel yönetimleri denetlemek",
      "Milletvekili seçimlerini yönetmek",
      "Bakanlar Kurulunu atamak",
      "Belediye bütçelerini onaylamak",
    ],
    dogruCevap: 0,
    aciklama: "Anayasa Mahkemesi'nin temel görevi, kanunların ve Cumhurbaşkanlığı kararnamelerinin Anayasaya uygunluğunu denetlemektir.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "Türkiye'de milletvekili seçilebilmek için gereken asgari yaş Anayasa'ya göre kaçtır?",
    secenekler: ["18", "21", "25", "30", "35"],
    dogruCevap: 0,
    aciklama: "2017 Anayasa değişikliğiyle milletvekili seçilme yaşı 18'e indirilmiştir.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "Seçme hakkı Türkiye'de kaç yaşını dolduran vatandaşlara tanınmıştır?",
    secenekler: ["16", "17", "18", "20", "21"],
    dogruCevap: 2,
    aciklama: "Anayasa'ya göre 18 yaşını dolduran her Türk vatandaşı seçme hakkına sahiptir.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "Mahalli idareler (yerel yönetimler) aşağıdakilerden hangisini kapsamaz?",
    secenekler: ["İl özel idaresi", "Belediye", "Köy", "Bakanlık", "Büyükşehir belediyesi"],
    dogruCevap: 3,
    aciklama: "Bakanlıklar merkezi yönetime bağlıdır; il özel idaresi, belediye ve köy mahalli idare birimleridir.",
  },
  {
    ders: "VATANDASLIK",
    soruMetni: "Anayasa'ya göre temel hak ve hürriyetler hangi durumda sınırlandırılabilir?",
    secenekler: [
      "Hiçbir şekilde sınırlandırılamaz",
      "Sadece cumhurbaşkanı kararıyla",
      "Anayasada öngörülen sebeplere bağlı olarak kanunla",
      "Belediye meclisi kararıyla",
      "Herhangi bir yönetmelikle",
    ],
    dogruCevap: 2,
    aciklama: "Anayasa'nın 13. maddesine göre temel hak ve hürriyetler, ancak Anayasanın ilgili maddelerinde belirtilen sebeplere bağlı olarak ve kanunla sınırlanabilir.",
  },

  // ---- GÜNCEL BİLGİLER (6) ----
  {
    ders: "GUNCEL",
    soruMetni: "Türkiye, NATO'ya (Kuzey Atlantik Antlaşması Örgütü'ne) hangi yıl üye olmuştur?",
    secenekler: ["1945", "1949", "1952", "1960", "1987"],
    dogruCevap: 2,
    aciklama: "Türkiye, 1952 yılında NATO'ya üye olmuştur.",
  },
  {
    ders: "GUNCEL",
    soruMetni: "Birleşmiş Milletler (BM) hangi yıl kurulmuştur ve Türkiye bu kuruluşun kurucu üyelerinden midir?",
    secenekler: [
      "1920, kurucu üyesidir",
      "1945, kurucu üyesidir",
      "1952, kurucu üyesi değildir",
      "1961, kurucu üyesidir",
      "1945, kurucu üyesi değildir",
    ],
    dogruCevap: 1,
    aciklama: "Birleşmiş Milletler 1945'te kurulmuştur ve Türkiye kurucu üyelerinden biridir.",
  },
  {
    ders: "GUNCEL",
    soruMetni: "Türkiye Cumhuriyeti'nin resmi para birimi aşağıdakilerden hangisidir?",
    secenekler: ["Türk Lirası", "Osmanlı Lirası", "Euro", "Kuruş", "Altın Lira"],
    dogruCevap: 0,
    aciklama: "Türkiye'nin resmi para birimi Türk Lirasıdır.",
  },
  {
    ders: "GUNCEL",
    soruMetni: "Türkiye Cumhuriyeti Anayasası'na göre devletin resmi dili nedir?",
    secenekler: ["Osmanlıca", "Türkçe", "Arapça", "Kürtçe", "Farsça"],
    dogruCevap: 1,
    aciklama: "Anayasa'nın 3. maddesine göre Türkiye Devleti'nin dili Türkçedir.",
  },
  {
    ders: "GUNCEL",
    soruMetni: "Türkiye, Avrupa Birliği'ne (o dönemki adıyla Avrupa Ekonomik Topluluğu'na) tam üyelik başvurusunu hangi yıl yapmıştır?",
    secenekler: ["1963", "1976", "1987", "1999", "2005"],
    dogruCevap: 2,
    aciklama: "Türkiye, tam üyelik başvurusunu 1987 yılında yapmıştır.",
  },
  {
    ders: "GUNCEL",
    soruMetni: "Türkiye'nin de kurucu üyeleri arasında bulunduğu, 1949'da kurulan ve insan hakları, demokrasi alanlarında çalışan kuruluş aşağıdakilerden hangisidir?",
    secenekler: ["Avrupa Birliği", "Avrupa Konseyi", "NATO", "Birleşmiş Milletler", "D-8"],
    dogruCevap: 1,
    aciklama: "Avrupa Konseyi 1949'da kurulmuştur; Türkiye kurucu üyeleri arasındadır.",
  },
];
