/**
 * KPSS deneme havuzlarinin ders ici konu dagilimi (son yillarin ÖSYM
 * dagilimlarina gore). Dizi sirasi = sinavdaki konu sirasi; seed, sorulari
 * bu siraya dizer ve sayilar tutmazsa yazmayi reddeder.
 */
import type { SeedSoru } from "./kpssDenemeOrtak";

type Dagilim = Record<SeedSoru["ders"], [konu: string, adet: number][]>;

const GUNCEL: [string, number][] = [["Güncel Bilgiler", 6]];

export const KONU_DAGILIMI: Record<"LISANS" | "ONLISANS" | "LISE", Dagilim> = {
  LISANS: {
    TURKCE: [
      ["Sözcükte Anlam", 1],
      ["Cümlede Anlam", 3],
      ["Sözcük Türleri", 2],
      ["Sözcükte Yapı ve Ekler", 1],
      ["Cümlenin Ögeleri", 1],
      ["Ses Olayları", 1],
      ["Yazım Kuralları", 1],
      ["Paragraf", 14],
      ["Paragrafta Anlatım Biçimleri", 2],
      ["Sözel Mantık", 4],
    ],
    MATEMATIK: [
      ["Temel Kavramlar", 3],
      ["Rasyonel ve Ondalık Sayılar", 2],
      ["Basit Eşitsizlikler", 1],
      ["Mutlak Değer", 1],
      ["Üslü Sayılar", 2],
      ["Köklü Sayılar", 1],
      ["Çarpanlara Ayırma", 1],
      ["Denklem Çözme", 1],
      ["Sayı Problemleri", 1],
      ["Yaş Problemleri", 1],
      ["Hareket Problemleri", 1],
      ["Yüzde-Kâr-Zarar ve Faiz Problemleri", 2],
      ["Kümeler", 1],
      ["Bağıntı ve Fonksiyon", 1],
      ["İşlem", 1],
      ["Olasılık", 1],
      ["Sayısal Mantık", 6],
      ["Özel Üçgenler", 1],
      ["Dörtgenler ve Çokgenler", 1],
      ["Analitik Geometri", 1],
    ],
    TARIH: [
      ["İslamiyet Öncesi Türk Devletleri", 1],
      ["İlk Müslüman Türk Devletleri", 2],
      ["Osmanlı Siyasi Tarihi", 6],
      ["Osmanlı Kültür ve Uygarlığı", 3],
      ["Kurtuluş Savaşı Hazırlık Dönemi", 4],
      ["Kurtuluş Savaşı Cepheleri", 3],
      ["İnkılap Tarihi", 2],
      ["Atatürk Dönemi İç ve Dış Politika", 2],
      ["Atatürk İlkeleri", 1],
      ["Çağdaş Türk ve Dünya Tarihi", 3],
    ],
    COGRAFYA: [
      ["Coğrafi Konum", 2],
      ["Yer Şekilleri ve Su Varlığı", 3],
      ["İklim ve Bitki Örtüsü", 3],
      ["Toprak ve Doğal Çevre", 1],
      ["Beşeri Coğrafya", 3],
      ["Tarım", 1],
      ["Madenler ve Enerji Kaynakları", 2],
      ["Sanayi", 1],
      ["Ulaşım", 1],
      ["Turizm", 1],
    ],
    VATANDASLIK: [
      ["Hukuka Giriş", 1],
      ["Anayasa ve Genel Esaslar", 1],
      ["Yasama", 2],
      ["Yürütme", 2],
      ["İdari Yapı", 3],
    ],
    GUNCEL,
  },
  ONLISANS: {
    TURKCE: [
      ["Sözcükte Anlam", 2],
      ["Cümlede Anlam", 1],
      ["Sözcük Türleri", 1],
      ["Sözcükte Yapı", 1],
      ["Cümlenin Ögeleri", 1],
      ["Ses Bilgisi", 1],
      ["Yazım Kuralları", 1],
      ["Noktalama İşaretleri", 1],
      ["Anlatım Bozuklukları", 1],
      ["Paragrafta Anlam", 15],
      ["Paragrafta Anlatım Biçimleri", 1],
      ["Sözel Mantık", 4],
    ],
    MATEMATIK: [
      ["Temel Kavramlar", 1],
      ["Sayılar ve EBOB-EKOK", 3],
      ["Rasyonel ve Ondalık Sayılar", 2],
      ["Mutlak Değer", 1],
      ["Üslü Sayılar", 1],
      ["Faktöriyel", 2],
      ["Denklem Çözme", 1],
      ["Oran-Orantı", 1],
      ["Sayı Problemleri", 1],
      ["Kesir Problemleri", 1],
      ["Yaş Problemleri", 1],
      ["İşçi ve Havuz Problemleri", 1],
      ["Hareket Problemleri", 1],
      ["Kümeler", 2],
      ["Fonksiyonlar", 1],
      ["Olasılık", 1],
      ["Grafik Problemleri", 2],
      ["Sayısal Mantık", 3],
      ["Geometri", 4],
    ],
    TARIH: [
      ["İslamiyet Öncesi Türk Kültür ve Medeniyeti", 1],
      ["İlk Türk-İslam Devletleri", 1],
      ["İlk Türk-İslam Kültür ve Medeniyeti", 2],
      ["Osmanlı Kuruluş ve Yükselme", 1],
      ["Osmanlı Duraklama (XVII. yy)", 1],
      ["Osmanlı Gerileme (XVIII. yy)", 1],
      ["Osmanlı Dağılma (XIX. yy)", 1],
      ["XX. Yüzyılda Osmanlı", 1],
      ["Osmanlı Kültür ve Medeniyeti", 4],
      ["Millî Mücadele", 4],
      ["İnkılap Tarihi", 5],
      ["Atatürk Dönemi İç ve Dış Politika", 1],
      ["Çağdaş Türk ve Dünya Tarihi", 4],
    ],
    COGRAFYA: [
      ["Coğrafi Konum", 2],
      ["İklim ve Bitki Örtüsü", 2],
      ["Fiziki Özellikler", 4],
      ["Nüfus ve Yerleşme", 2],
      ["Tarım", 1],
      ["Hayvancılık", 1],
      ["Madenler ve Enerji Kaynakları", 2],
      ["Sanayi", 1],
      ["Ulaşım", 1],
      ["Ticaret", 1],
      ["Turizm", 1],
    ],
    VATANDASLIK: [
      ["Temel Hukuk Kavramları", 3],
      ["Yasama", 1],
      ["Yürütme", 2],
      ["Yargı", 1],
      ["İdare Hukuku", 2],
    ],
    GUNCEL,
  },
  LISE: {
    TURKCE: [
      ["Sözcükte Anlam", 2],
      ["Cümlede Anlam", 2],
      ["Dil Bilgisi", 3],
      ["Ses Bilgisi", 1],
      ["Yazım Kuralları", 1],
      ["Noktalama İşaretleri", 1],
      ["Anlatım Bozuklukları", 1],
      ["Paragraf", 15],
      ["Sözel Mantık", 4],
    ],
    MATEMATIK: [
      ["Temel Kavramlar", 2],
      ["Rasyonel Sayılar", 2],
      ["Köklü Sayılar", 1],
      ["Üslü Sayılar", 1],
      ["Matematiksel İlişkilerden Yararlanma", 6],
      ["Problemler", 8],
      ["Tablo ve Grafik", 3],
      ["Sayısal Mantık", 4],
      ["Temel Geometri", 3],
    ],
    TARIH: [
      ["İlk Türk Devletleri", 1],
      ["Türk-İslam Devletleri", 2],
      ["Osmanlı Devleti", 9],
      ["Kurtuluş Savaşı", 3],
      ["Atatürk İlke ve İnkılapları", 9],
      ["Çağdaş Türk ve Dünya Tarihi", 3],
    ],
    COGRAFYA: [
      ["Coğrafi Konum", 1],
      ["İklim ve Bitki Örtüsü", 2],
      ["Fiziki Özellikler", 4],
      ["Beşeri Özellikler", 3],
      ["Ekonomik Özellikler", 8],
    ],
    VATANDASLIK: [
      ["Temel Hukuk Kavramları", 3],
      ["Yasama-Yürütme-Yargı", 4],
      ["İdare Hukuku", 2],
    ],
    GUNCEL,
  },
};
